ingress:
  className: nginx-external
  annotations:
    # cert-manager.io/cluster-issuer: "barrage-dev"
    ## The following annotation is to limit access to the ingress
    nginx.ingress.kubernetes.io/whitelist-source-range: 172.21.252.1/24, 172.21.240.245/32
    