ingress:
  className: nginx-external
  annotations:
  #   cert-manager.io/cluster-issuer: "barrage-le-production"
  #   ## The following annotation is to limit access to the ingress
    nginx.ingress.kubernetes.io/whitelist-source-range: 172.21.252.1/24, 172.21.240.245/32
    
barrage:
  vault:
    role: "llmao-web-app-k8-stg"
    moduleWorkspace: "llmao/data/deploy-web-app-stg"